apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-10-03T01:39:20Z"
  generation: 1
  labels:
    app: deploy-1
  name: deploy-1
  namespace: default
  resourceVersion: "69005"
  uid: 9cbebd5a-a9f0-469e-999a-502a95c4e45b
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: deploy-1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: deploy-1
    spec:
      containers:
      - image: aminking/project:development.56
        imagePullPolicy: IfNotPresent
        name: project
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstrestartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2021-10-03T01:59:15Z"
    lastUpdateTime: "2021-10-03T02:11:13Z"
    message: ReplicaSet "deploy-1-8678567d8d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-10-03T02:30:17Z"
    lastUpdateTime: "2021-10-03T02:30:17Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 1
  replicas: 1
  unavailableReplicas: 1
  updatedReplicas: 1
