apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2021-10-03T01:40:27Z"
  labels:
    app: deploy-1
  name: service-dep
  namespace: default
  resourceVersion: "64401"
  uid: e0a03ad7-c8ff-4e00-982f-28270731ca2d
spec:
  clusterIP: 10.99.219.8
  clusterIPs:
  - 10.99.219.8
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32119
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: deploy-1
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
